# .github/workflows/build.yml
name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed PDFParser/app.py

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: PDFCSVTool.exe
        path: PDFParser/dist/app.exe
